[package]
name = "synacor-challenge"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.2"
crossterm = "0.27.0"
ratatui = { version = "0.26.0", features = ["unstable-rendered-line-info"]}
